name: Frontend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'front/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'front/**'
      - '.github/workflows/test.yml'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: resume-frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd resume-frontend
        npm ci
    
    - name: Run frontend tests
      run: |
        cd resume-frontend
        npm run test:ci
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: resume-frontend/coverage/lcov.info
        flags: frontend
        name: frontend-coverage

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: resume-frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd resume-frontend
        npm ci
    
    - name: Run frontend linting
      run: |
        cd resume-frontend
        npm run lint
